### ISSUE TITLE
Todolist

### ISSUE THREAD

**Issue by Lycea** [Lycea/Rogue#3]
POI Loading and adding things simpler:
- [x] Revamp mob loading / Add dynamic mob loading
- [x] Revamp item loading / Add dynamic item loading
- [ ] Add dynamic AI loading
- [ ] Add dynamic Item function loading

POI usability
- [x] Revamp window system to be more visible
- [x] Make items stackable
(  make scrolling view )

POI api
- [ ] Convert some constructors from taken in a huge list of parameters to take in a table/object 
      which also have a default object initialisation in it so that you only need to fill in the things you  
      need, so that creating entities and some other stuff will be much simpler.

- [ ] put all global variables which are scattered around into a other global file just for informativity
- [ ] prefix globals with some kind of 

FIXES needed
- [ ] Fix exiting of the game that you don't just exit the whole game ...
- [ ] Change ray traceing to brahams , will help for better FOV (check where I did it before ...)
- [x] Fix z-fighting of items, it happens cause all items are resorted on draw each time , do this only
      if needed maybe. Also see #20 which also refers to this problem

**Comment by Lycea** [comment]
Working on dynamic mob loading,got a loader system only need to verify how to load up the chances efficiently,the same will most likely also work for items
